### PR TITLE
[#293] Fix: Template tasks may delete new tasks

### LINKED ISSUE #293: Template tasks may delete new tasks
I've just found a problem in the implementation of #247, in particular this part:

> b) delete the empty task when copying tasks from other days or creating the first task from a template.

Steps to reproduce:
1. Open a new, empty day.
2. Fill the empty task with some init/end time, project, etc.
3. Now click on a template button to add a second task.

Expected result: the template task is added, so there are two tasks now.
Actual result: the template task deletes the existing task, even when it's not empty any more.

### PR DESCRIPTION
**Pull request by tonythomas01**
Fix #293

### CODE REVIEW

File: web/js/tasks.js [hunk 1]
```diff
@@ -1318,6 +1318,13 @@ Ext.onReady(function(){
 
     summaryStore.load();
 
+    function isUnToched(taskRecord) {
+        if(taskRecord.get('text') == '' && taskRecord.get('descripton') == '' && taskRecord.get('initTime') == ''
```
Comment (jaragunde) [inline web/js/tasks.js]: `description` is not a field of `taskRecord`. Besides, there was a typo :D

I think it's enough with `text`, `initTime` and `projectId`.

**Comment by jaragunde** [comment]
Now, the empty task never disappears when you create a task from template or use the "copy tasks" button.
